@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":  "Raphael Teste",
  "email": "raphaelteste@email.com.br",
  "password": "senha"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe2@example.com",
  "password": "123456"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova Pergunta 5",
  "content": "Conteúdo da nova pergunta 5"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-pergunta-5
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name upload_attachment
POST {{baseUrl}}/attachments/
Content-Type: application/json
Authorization: Bearer {{authToken}}